### ISSUE TITLE
brew goes into infinite recursion...

### ISSUE THREAD

**Issue by stvhay** [Homebrew/brew#13896]
### `brew config` output

```shell
brew config 2>&1 /dev/null

HOMEBREW_VERSION: 3.6.2-6-g8de3e93
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8de3e93715d6c19529d5d5aa7cbb10f20d947096
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c1b0e95c0069cb2a49fac440301d0d7c8125c557
Core tap last commit: 51 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 1
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: single-core 64-bit unknown_0x6_0x5c

without the /dev/null redirect:

HOMEBREW_VERSION: 3.6.2-6-g8de3e93
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8de3e93715d6c19529d5d5aa7cbb10f20d947096
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c1b0e95c0069cb2a49fac440301d0d7c8125c557
Core tap last commit: 52 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
Error: stack level too deep
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/pathname.rb:42:in `chop_basename'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/pathname.rb:359:in `plus'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/pathname.rb:351:in `+'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:83:in `block in gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:38:in `system_gcc_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:33:in `build_system_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:11:in `block in locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:84:in `block in gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:38:in `system_gcc_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:33:in `build_system_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:11:in `block in locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:84:in `block in gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:38:in `system_gcc_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:33:in `build_system_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:11:in `block in locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `locate'
....
```

### `brew doctor` output

```shell
Error: stack level too deep
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:38:in `system_gcc_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:33:in `build_system_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:11:in `block in locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:84:in `block in gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:38:in `system_gcc_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:33:in `build_system_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:11:in `block in locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:84:in `block in gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:38:in `system_gcc_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:33:in `build_system_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:11:in `block in locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `locate'
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to run brew install gcc as part of a fresh install.

### What happened (include all command output)?

(λ=0) hays@clio2 ~ $ brew install gcc 2>&1 | more
Error: stack level too deep
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:38:in `system_gcc_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:33:in `build_system_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:11:in `block in locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:84:in `block in gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:38:in `system_gcc_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:33:in `build_system_too_old?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:11:in `block in locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/development_tools.rb:10:in `locate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:84:in `block in gcc_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/development_tools.rb:82:in `fetch'
...

### What did you expect to happen?

Installation of gcc.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
This happened on a non-fresh install when I did a brew update. I did a fresh install and now it does it on brew install gcc.
```

**Comment by carlocab** [comment]
What distro are you on? And which version?

CC @Bo98

**Comment by carlocab** [comment]
Also, what is the output of `which -a gcc` and `file /usr/bin/gcc`?

**Comment by stvhay** [comment]
@carlocab 

I am on a Synology DSM. It doesn't have a recognizable distro, but it is linux.

While there was (linuxbrew) gcc before and I got the same error--on this fresh install there is no gcc. There is no file /usr/bin/gcc.

**Comment by stvhay** [comment]
If it is helpful, I followed these instructions to install: https://community.synology.com/enu/forum/1/post/153781

This worked like 1 week ago.

**Comment by carlocab** [comment]
Homebrew needs a pre-existing tool chain to function.

We can and should fix the infinite recursion, but I don't think you'll get much use out of `brew` on your NAS even after that's done.

**Comment by stvhay** [comment]
Homebrew itself is telling me to install gcc (from a bottle) so it does seem like this way of installing was supported before.

**Comment by carlocab** [comment]
It is not: https://docs.brew.sh/Homebrew-on-Linux#requirements

There is, unfortunately, an extremely wide range of possible Linux configurations, so `brew` itself cannot always accurately detect when you are running on a system that is not supported.

**Comment by stvhay** [comment]
Well, good luck with your infinite recursion problem. 

It is too bad you cannot support this--I am probably not the only one trying to get this installed on systems without a developer toolchain.  And, as I said before, I successfully installed this last week and had a working gcc (due to brew install gcc successfully installing from a bottle), and was still faced with this error.

**Comment by dawidd6** [comment]
You could not have installed brewed `gcc` successfully without host `gcc` present even before recent changes, because the postinstall steps wouldn't execute properly. Look at this code:
https://github.com/Homebrew/homebrew-core/blob/c1b0e95c0069cb2a49fac440301d0d7c8125c557/Formula/gcc.rb#L168

Nevertheless this dirty patch for `brew` solves the recursion issue:
```diff
diff --git a/Library/Homebrew/development_tools.rb b/Library/Homebrew/development_tools.rb
index e1288c9bc..83dc525b0 100644
--- a/Library/Homebrew/development_tools.rb
+++ b/Library/Homebrew/development_tools.rb
@@ -81,13 +81,14 @@ class DevelopmentTools
     def gcc_version(cc)
       (@gcc_version ||= {}).fetch(cc) do
         path = HOMEBREW_PREFIX/"opt/#{CompilerSelector.preferred_gcc}/bin"/cc
-        path = locate(cc) unless path.exist?
-        version = if path &&
-                     (build_version = `#{path} --version`[/gcc(?:(?:-\d+(?:\.\d)?)? \(.+\))? (\d+\.\d\.\d)/, 1])
-          Version.new build_version
-        else
-          Version::NULL
-        end
+        #path = locate(cc) unless path.exist?
+        #version = if path &&
+        #             (build_version = `#{path} --version`[/gcc(?:(?:-\d+(?:\.\d)?)? \(.+\))? (\d+\.\d\.\d)/, 1])
+        #  Version.new build_version
+        #else
+        #  Version::NULL
+        #end
+        version = Version::NULL
         @gcc_version[cc] = version
       end
     end
```

Note that even after applying above patch you won't be able to install brewed `gcc`  without host `gcc` present, as I explained earlier. Relevant piece of log from brewed `gcc` installation without host `gcc`:
```
==> Installing gcc
==> Pouring gcc--12.2.0.x86_64_linux.bottle.1.tar.gz
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall gcc
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0: 1,623 files, 306.4MB
==> Running `brew cleanup gcc`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

The exit status is 1 and the bottle is poured but `gcc` is not installed properly.

**Comment by carlocab** [comment]
Actually, now that I think about it: GCC's runtime libraries _could_ work despite the `post_install` failure. You just won't be able to build anything with the `gcc` you just installed.

**Comment by stvhay** [comment]
Here is a reference to this possibly working in the past, but its fine if you are not interested in or can't support this method of installation https://github.com/Linuxbrew/brew/issues/893

**Comment by stvhay** [comment]
The strange thing is, believe me or not, I had installed linuxbrew with quite a few packages and things seemed to be working just fine. its just this morning's brew update somehow broke everything.

**Comment by Bo98** [comment]
Should be fixed now, thanks!
