### ISSUE TITLE
Fresh install of macOS Sierra complains of outdated XCode 7.3

### ISSUE THREAD

**Issue by rwong48** [Homebrew/brew#1393]
After a fresh install of macOS 10.12.1 Sierra, the first thing that I do is install Homebrew:

```
xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew install duti
```

But on `brew install`, I get the following:

```
Error: Your Xcode (7.3) is outdated.
Please update to Xcode 8.0 (or delete it).
Xcode can be updated from the App Store.
```

We don't need XCode, we didn't install XCode, and I haven't been able to find any pre-packaged XCode in the OS. There's no `/Applications/Xcode.app`, and `/Library/Developer/` only contains `CommandLineTools`.

I was reading #1231, but can't figure out.. How do I go about removing Xcode 7.3? Or is Homebrew's detection failing, somehow?

**Comment by MikeMcQuaid** [comment]
What does `mdfind -name Xcode.app` output?

**Comment by rwong48** [comment]
Nothing :(

I was able to get this to work by skipping `xcode-select --install` to begin with. I remember that the Brew installer used to always mention this after a fresh install, but now it seems that the Brew installer fetches CLT 10.11/XCode 7.3.

Then, when I try to install a package, it tells me to update CLT from the App Store, which also works, then Brew works fine.

So the suspect is running `xcode-select --install` before trying to attempt any of this.

**Comment by MikeMcQuaid** [comment]
This will likely be fixed by https://github.com/Homebrew/install/pull/86

**Comment by thesandbender** [comment]
It seems like the macOS 10.12.2 and latest CLT tools may have broken this again.  I only have XCode 8.2 installed and brew was working immediately before the update.  After the update `brew doctor` and `brew install <pkg>` are both reporting:

`Warning: Your Xcode (7.3) is too outdated.`

brew config | grep Xcode reports : 

`Xcode: 8.2`

cc -v reports : 

`Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

xcode-select --install reports:

`xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

**Comment by MikeMcQuaid** [comment]
@thesandbender What do `mdfind -name Xcode.app` and `xcode-select --print-path` output?

**Comment by thesandbender** [comment]
`mdfind -name Xcode.app` -> nothing (? - see below)
`xcode-select --print-path` -> `/Library/Developer/CommandLineTools`

What's weird is Xcode.app most certainly is there:

`ls -l /Applications/X*` gives:
`/Applications/Xcode.app:
total 0
drwxr-xr-x  17 root  wheel  578 Dec 15 12:37 Contents`

I've verify that Spotlight is running and indexing my drive.  What's weird is mdfind is not return any app bundles for me if I use `-name` (doesn't find Mail.app, Terminal.app, etc) but if I just run `mdfind Xcode.app` it does return it along with other things.  Using `-name` with an existing normal file (e.g. text file) or directory (e.g. Applications) works fine as well.  It seems`mdfind -name` doesn't work with application bundles?

I forced Spotlight to reindex my drive and will follow up in a bit but as I mentioned brew was working fine immediately before the update and the update was the only thing that changed (and I have a standard XCode install, only the current version in /Applications).

**Comment by thesandbender** [comment]
Completely rebuilt the Spotlight database and it's still not finding Xcode.app using `mdfind -name`:
`mdfind -name Xcode.app` -> nothing
`mdfind -name Xcode` -> reports `/Applications/Xcode.app` (as well as several other things)
`mdfind "kMDItemFSName = 'Xcode.app'"` -> reports `/Applications/Xcode.app`

**Comment by thesandbender** [comment]
I finally got to the bottom of this.  About a month ago I did a complete reinstall of my laptop and before I did a `cp -apR` of my system drive to folder on my external drive.  That did have a copy of Xcode but was it was not "installed" on the refreshed system i.e. they were just files on a drive, it wasn't an installed copy, wasn't on the path and I had never run XCode (or anything for that matter) for that backup directory.  Regardless macOS found it and latched onto it, AppStore in that folder but not actually installed on the new system as "installed" (but you couldn't launch or use them).

The drive is only plugged in at home so brew was working at the office before the install.  Removing the directory fixed the issue with brew.

**Comment by MikeMcQuaid** [comment]
Glad you've got it sorted. It's on my TODO list to handle these weird edge cases.

**Comment by paustria** [comment]
Just install Xcode on App Store. It will take a while (approx. 5-10 mins) for installing Xcode 8.3.3.

**Comment by rwong48** [comment]
@paustria the whole point of this is so that you can install Homebrew without the entire Xcode suite - only the command-line tools (if at all).

**Comment by MikeMcQuaid** [comment]
@rwong48 That works.
