### ISSUE TITLE
luarocks and permissions

### ISSUE THREAD

**Issue by telemachus** [Homebrew/brew#1938]
- [x ] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ?] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

I put a question in the last one, because I'm not sure how to classify this problem, to be honest. That is, I don't know if it's a problem with the lua formula or how `brew` handles permissions more generally. Here's the issue:

    $ luarocks-5.3 install  luaposix
    
    Error: Your user does not have write permissions in /usr/local
    -- you may want to run as a privileged user or use your local tree with --local.

I take it that this is a mismatch between how `brew` now handles permissions and what `luarocks` expects/needs. I can install locally, but then I have to do manual twiddling of my Lua environment for scripts, etc. I can use `sudo` before calling `luarocks-5.3 install`, but then I worry that `brew doctor` will complain later.

So my question is this: how can `brew` users make both `brew` and `luarocks` happy in terms of default installs to `/usr/local` subdirectories?

/cc @hishamhm

**Comment by MikeMcQuaid** [comment]
How did this work previously?

**Comment by telemachus** [comment]
Previously that install would have worked, and it placed modules (and executables) in subfolders as follows:

    $ ls /usr/local/lib/luarocks/rocks-5.3/
    getopt		luacheck	luaposix	optparse	stdlib
    ldoc		luacov		lyaml		penlight	tableutils
    lpeg		luafilesystem	manifest	specl		tapered
    lua-glob	luamacro	markdown	split		utilitybelt

**Comment by DomT4** [comment]
Sigh, I meant to flag this in the past after Homebrew returned `/usr/local` to its default permissions. One of the things that got left down the back of the sofa after I left.

IMO, this is more-or-less `luarocks` issue. Their check is overly broad; it checks whether `luarocks` can write to the whole directory rather than checking if it can write to `bin`, `lib/luarocks`, etc specifically.

**Comment by telemachus** [comment]
Sorry, this has been closed, but I can't see a resolution. What is the proposal going forward?

Again, to be clear, Homebrew currently installs luarocks, but it won't work normally without `sudo` (which it will recommend). I think it's in Homebrew's interest to have some solution  or advice, so that people don't end up installing lots of things via `sudo` (with potential further permission problems down the line).

**Comment by hishamhm** [comment]
@telemachus I believe this is already fixed in the `luarocks-3` branch. 

In [current master](https://github.com/luarocks/luarocks/blob/7f67011db75e671068b7f02d5489491f512bf816/src/luarocks/fs/lua.lua#L827):

```lua
   for _, dir in ipairs { cfg.rocks_dir, root_dir } do
```

In [`luarocks-3`](https://github.com/luarocks/luarocks/blob/luarocks-3/src/luarocks/fs/lua.lua#L838):

```lua
   for _, directory in ipairs { cfg.rocks_dir, cfg.deploy_lua_dir, cfg.deploy_bin_dir, cfg.deploy_lua_dir } do
```

The specific directories are checked.

**Comment by telemachus** [comment]
@hishamhm That's good news. However, that's not the luarocks that Homebrew installs, and I'm not sure when/if/how it will become part of Homebrew's Lua installation. I can install that *over* what Homebrew does, or create my own formula, but that doesn't fix the larger problem that the current `lua` install is more or less crippled.
