### ISSUE TITLE
Use special exit code for `HOMEBREW_FORBIDDEN_`-related failures

### ISSUE THREAD

**Issue by purajit** [Homebrew/brew#19939]
### Verification

- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Currently, `brew install` and `brew bundle` exit `1` when a formula/cask 
wasn't installed because it was forbidden.

Particularly in the case for `bundle`, I think it would be reasonable that you
just want to skip the forbidden formulae, and pretend like it succeeded if
that was the only reason for failure, especially if it didn't lead to failures
in installing other packages.

Since this is different from a true failure to install a package, it would be
useful to exit differently so that setup scripts can handle it how they wish. 

```sh
> HOMEBREW_FORBIDDEN_FORMULAE=redis brew install redis
==> Downloading https://ghcr.io/v2/homebrew/core/redis/manifests/8.0.0
Already downloaded: ...
Error: The installation of redis was forbidden by you
in `HOMEBREW_FORBIDDEN_FORMULAE`.

> echo $?
1

> HOMEBREW_FORBIDDEN_FORMULAE=redis brew bundle --file <(echo 'brew "redis"')
Installing redis
==> Downloading https://ghcr.io/v2/homebrew/core/redis/manifests/8.0.0
Already downloaded: ...
Error: The installation of redis was forbidden by you
in `HOMEBREW_FORBIDDEN_FORMULAE`.
Installing redis has failed!
`brew bundle` failed! 1 Brewfile dependency failed to install

> echo $?
1
```

### What is the motivation for the feature?

Particularly in the case of `bundle`, it is a command that often gets run as part
of a larger setup script, and being able to correctly fail on real errors, and
simply continue on these kinds of errors, would be very useful.

### How will the feature be relevant to at least 90% of Homebrew users?

Admittedly, this specific request is an intersection of two niches. However, in 
in general, having different exit codes for different failures is very useful for 
automation, and Homebrew commands are very often used as part of an 
automation. 

### What alternatives to the feature have been considered?

* Capturing stdout and looking for `was forbidden by you`, and using that as a proxy, 
which works pretty much like how an exit code would, but is messier and more 
susceptible to Homebrew changes
* Not using `set -e` in setup scripts, which is extremely non-ideal

**Comment by MikeMcQuaid** [comment]
> Particularly in the case for `bundle`, I think it would be reasonable that you
> just want to skip the forbidden formulae, and pretend like it succeeded if
> that was the only reason for failure, especially if it didn't lead to failures
> in installing other packages.

@purajit Is this a request specifically for `brew bundle`? Can you mock up the desired output you'd want to see in that case?

Stepping back: can you provide a more specific example of your particular case and what's failing? Just trying to understand the problem better before we jump to a solution. Thanks! ❤

**Comment by purajit** [comment]
> @purajit Is this a request specifically for brew bundle? 

I think it's mostly applicable to `bundle`, but I'm not opposed to it being done for the normal 
`install` case as well.

> Can you mock up the desired output you'd want to see in that case?

```sh
# Minimal solution: No change in output - just the exit code!
> HOMEBREW_FORBIDDEN_FORMULAE=redis brew bundle --file <(echo 'brew "redis"')
Installing redis
==> Downloading https://ghcr.io/v2/homebrew/core/redis/manifests/8.0.0
Already downloaded: ...
Error: The installation of redis was forbidden by you
in `HOMEBREW_FORBIDDEN_FORMULAE`.
Installing redis has failed!
`brew bundle` failed! 1 Brewfile dependency failed to install

> echo $?
2

# Potential addition: allow ignoring such errors
> HOMEBREW_FORBIDDEN_FORMULAE=redis brew bundle --ignore-forbidden --file <(echo 'brew "redis"')
Installing redis
==> Downloading https://ghcr.io/v2/homebrew/core/redis/manifests/8.0.0
Already downloaded: ...
Warning: The installation of redis was forbidden by you in `HOMEBREW_FORBIDDEN_FORMULAE`.
Installing redis was skipped!
`brew bundle` failed! 1 Brewfile dependency failed to install

> echo $?
0
```

> Stepping back: can you provide a more specific example of your particular case and what's failing? 

For example, let's say you have a setup script that does
```sh
set -e

# some prior steps

brew bundle

# some later steps
```

Currently, this script will fail at the `brew bundle`. We can't simply ignore the exit code `1`,
since that could imply something serious went wrong, and we cannot continue with setup until that
is resolved. However, if the user has just opted to not wish to use one of the packages there (for
instance, maybe the `Brewfile` has `redis`, and they wish to use their own installation of `valkey`
instead), we would rather continue. If `brew bundle` gave a different exit code for this case, we
could simply catch and ignore it, allowing the setup script to continue, while also being certain
that nothing deeper/more critical has failed.

**Comment by MikeMcQuaid** [comment]
> I think it's mostly applicable to `bundle`, but I'm not opposed to it being done for the normal
> `install` case as well.

@purajit Let's stick to what you personally want/need: is your use-case here specifically for `brew bundle` or for `brew install` as well?

Similarly, in your case: are the people setting `HOMEBREW_FORBIDDEN_FORMULAE` and the people running `brew bundle` different?

---

I'm leaning towards saying this doesn't make sense to have a `0` exit code. `brew bundle` is specifically requesting installation of a package and it fails. That doesn't seem like it should be successful. I understand the addition of `--ignore-forbidden` would make it make more sense here but I'm still not sure I understand why you'd want to have it in the `Brewfile` if it's forbidden?

**Comment by MikeMcQuaid** [comment]
> However, the `Brewfile` has a couple choices that certain individuals want to override, and so forbid the installation of those formulae.

Ok, this is more obvious then. `HOMEBREW_FORBIDDEN_FORMULAE` and friends are not designed for this. `HOMEBREW_BUNDLE_BREW_SKIP` provides this functionality for `brew bundle` which also returns a `0` exit code. It's documented in `man brew` but not in https://docs.brew.sh/Brew-Bundle-and-Brewfile. Is that why you missed it?

**Comment by purajit** [comment]
Oh wow - perfect, yeah - that's what I wanted. I had even done a `man brew | grep SKIP` but didn't find it - but yes, that's why! I'll check why grepping doesn't find it, I suspect escape sequence shenanigans.
