### ISSUE TITLE
Problems installing from bottle with different package name capitalisation

### ISSUE THREAD

**Issue by vytis** [Homebrew/brew#2613]
# Please always follow these steps:
- [ ] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
--------------------
I have problems updating a package if I capitalize the name of it, but it works fine with all-lowercase name. Checked with other packages and it works fine with different capitalization, so I could not confirm this is NOT a problem with this package specifically. 

**Steps to reproduce**
1. have outdated version of [Carthage](https://github.com/Carthage/Carthage)
2. do `brew update Carthage` (notice the capitalisation)

**Expected result**
Package is updated the same as with `brew update carthage` (with lowercase c).

**Actual result**
With capitalized package name it fails to download a bottle:
```
$ brew upgrade Carthage                                                                                    

==> Upgrading 1 outdated package, with result:
Carthage 0.22.0
==> Upgrading Carthage
==> Downloading https://homebrew.bintray.com/bottles/Carthage-0.22.0.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "Carthage"
Download failed: https://homebrew.bintray.com/bottles/Carthage-0.22.0.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Using the sandbox
<continues to build everything...>
```

However it works fine with lowercase package name. Notice that the package name in URL and other places is capitalized as provided (different from the previous example):

```
$ brew upgrade carthage  

==> Upgrading 1 outdated package, with result:
carthage 0.22.0
==> Upgrading carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.22.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring carthage-0.22.0.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions

fish completions have been installed to:
  /usr/local/share/fish/vendor_completions.d
==> Summary
🍺  /usr/local/Cellar/carthage/0.22.0: 64 files, 22.6MB
```

**brew config**
```
HOMEBREW_VERSION: 1.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8cba0352e0be94263e2ed96c98bf93d8f2fce8ef
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 85f0d7269350b20823e23ceef082861d70d075c5
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.3.3/bin/ruby
Java: 1.8.0_131
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

**brew doctor**
```
Your system is ready to brew.
```

**Comment by MikeMcQuaid** [comment]
I cannot reproduce this, I'm afraid. If you can provide step-by-step instructions that you can reproduce I'll try the same. Sorry and thanks for a good report.

**Comment by vytis** [comment]
I have managed to reproduce the same issue again on multiple machines (both Sierra and High Sierra). Spent a bit of time getting all the steps right - however I could not reproduce the issue with other outdated formulae. The spec for Carthage is pretty simple, but I cannot rule out that something is wrong there - https://github.com/Homebrew/homebrew-core/blob/master/Formula/carthage.rb

So the steps are:

* Have an older version of Carthage installed (anything that is less than 0.27.0 at the moment)
* do `brew upgrade Carthage` (note the uppercase `C` in the name)

The output I get is similar to what I specified in the original issue:

```
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
Carthage 0.27.0
==> Upgrading Carthage
==> Downloading https://homebrew.bintray.com/bottles/Carthage-0.27.0.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "Carthage"
Download failed: https://homebrew.bintray.com/bottles/Carthage-0.27.0.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

Once again if I do `brew upgrade carthage` (note the lowercase `c` in the name) everything works as expected:

```
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
carthage 0.27.0
==> Upgrading carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.27.0.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/e4/e4a1e11c3681944b30c24c7772c661e9bbac55fa6e09ba5b8db055f6d389ee4a?__gd
######################################################################## 100.0%
==> Pouring carthage-0.27.0.sierra.bottle.tar.gz
```

After successful install I managed to reproduce the issue again by removing the newest version from `/usr/local/Cellar/carthage` and removing `carthage-0.27.0.sierra.bottle.tar.gz` from `~/Library/Caches/Homebrew/Cask/`.

So my take on this issue is - there is some part in code that doesn't lowercase user input and passes around capitalized version of the formula name. Since the same issue was not triggered with few other formulae I tried (wget, openssl, python, rust), there must be something special in Carthage formula that triggers it.

The other formulae that were upgraded successfully all had lowercased names logged in the output even when I passed uppercased versions of them. For Carthage this seems different - if I supply uppercased name (`Carthage`) then in the output I also see `Carthage` and vice-versa.

**Comment by apjanke** [comment]
I'm unable to reproduce this as well, when upgrading from Carthage 0.26.2 to 0.27.0 on a 10.12.6 Sierra system.

```
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ git checkout 3f7ef45215
Note: checking out '3f7ef45215'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 3f7ef45215... groonga: update 7.0.9 bottle.
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ 3f7ef45215]
$ brew install Carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.26.2.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring carthage-0.26.2.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/carthage/0.26.2: 75 files, 25.9MB
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ 3f7ef45215]
$ git checkout master
Previous HEAD position was 3f7ef45215... groonga: update 7.0.9 bottle.
Switched to branch 'master'
Your branch is behind 'origin/master' by 14 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ brew upgrade Carthage
==> Upgrading 1 outdated package, with result:
carthage 0.27.0
==> Upgrading carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.27.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring carthage-0.27.0.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/carthage/0.27.0: 69 files, 26.6MB
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$
```

There doesn't seem (to my eyes) to be anything in the `carthage` formula that would affect this, especially since this is pulling from the bottle archives instead of a source install.

Any chance you're running with a case-sensitive filesystem for your `~/Library/Caches` directory? And can you do a `brew update` too, just in case?

The fact that there was a `carthage` bottle in the `~/Library/Caches/Homebrew/Cask` directory (per your description) suggests this might be a Homebrew Cask migration issue instead of a simple upgrade issue. Though looking through `brew log carthage` indicates this has been a core Homebrew formula (not a cask) since at least 2014.

**Comment by apjanke** [comment]
BTW, I went back even further, doing an install from the `carthage` formula prior to your original May 9, 2017 post, and was also unable to reproduce the issue.

```
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ git checkout 4b6fec48c5
Note: checking out '4b6fec48c5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 4b6fec48c5... mysql-sandbox: update 3.2.06 bottle.
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ 4b6fec48c5]
$ brew install Carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.20.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring carthage-0.20.1.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/carthage/0.20.1: 64 files, 22.4MB
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ 4b6fec48c5]
$ git checkout master
Previous HEAD position was 4b6fec48c5... mysql-sandbox: update 3.2.06 bottle.
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ brew upgrade Carthage
==> Upgrading 1 outdated package, with result:
carthage 0.27.0
==> Upgrading carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.27.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring carthage-0.27.0.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/carthage/0.27.0: 69 files, 26.6MB
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$
```

This might be a system-dependent issue, or something we've already fixed: your `brew config` from the original report is saying Homebrew 1.2.0; we're up to Homebrew 1.4.3 now.

**Comment by vytis** [comment]
I have trouble following your steps of installing older version of Carthage - for me it always installs 0.27.0 even if I check out that commit of `homebrew-core`.

Maybe you can also try installing carthage with lowercase name (`brew install carthage`)? That's the only thing that seems different from what I did. I have seen this issue on 4 different machines now, so it should be something more than just weird configuration on my side. BTW I checked and I am on case-insensitive file system, nothing special there.

**Comment by apjanke** [comment]
You'll need to do a `brew rm --force carthage` first to get a clean base to run these instructions from. Sorry; I should have included that in the script output.

Same results here with a `brew install carthage`, lower case.

```
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ brew rm --force carthage
Uninstalling carthage... (133 files, 49MB)
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ git checkout 4b6fec48c5
Note: checking out '4b6fec48c5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 4b6fec48c5... mysql-sandbox: update 3.2.06 bottle.
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ 4b6fec48c5]
$ brew install carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.20.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring carthage-0.20.1.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/carthage/0.20.1: 64 files, 22.4MB
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ 4b6fec48c5]
$ git checkout master
Previous HEAD position was 4b6fec48c5... mysql-sandbox: update 3.2.06 bottle.
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ brew upgrade Carthage
==> Upgrading 1 outdated package, with result:
carthage 0.27.0
==> Upgrading carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.27.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring carthage-0.27.0.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/carthage/0.27.0: 69 files, 26.6MB
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ brew rm --force carthage
Uninstalling carthage... (133 files, 49MB)
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ git checkout 4b6fec48c5
Note: checking out '4b6fec48c5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 4b6fec48c5... mysql-sandbox: update 3.2.06 bottle.
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ 4b6fec48c5]
$ rm ~/Library/Caches/Homebrew/*.gz
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ 4b6fec48c5]
$ brew install carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.20.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring carthage-0.20.1.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/carthage/0.20.1: 64 files, 22.4MB
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ 4b6fec48c5]
$ git checkout master
Previous HEAD position was 4b6fec48c5... mysql-sandbox: update 3.2.06 bottle.
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ brew upgrade carthage
==> Upgrading 1 outdated package, with result:
carthage 0.27.0
==> Upgrading carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.27.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring carthage-0.27.0.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/carthage/0.27.0: 69 files, 26.6MB
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$
```

**Comment by apjanke** [comment]
If you want to go crazy, you could give me SSH access to one of your machines so I could see this in action.

**Comment by vytis** [comment]
So it seems whatever was causing it got cleaned with `brew rm`. However on one of our build machines the same thing is still happening, maybe there are some hints still present there that I could look into...

**Comment by apjanke** [comment]
> Unfortunately I can't give you SSH access to these machines as they are my colleagues work computers :)

That just means you're sane. :)

> Is there a way to do the upgrade to an intermediate version by checking out homebrew-core at some other point?

Yep. You can `git checkout` your homebrew-core tap to any commit in the history. Do a `brew log carthage` to get a list of commits relevant to the `carthage` formula. If you're *always* getting 0.27.0 installed regardless of your homebrew-core checkout state, something else might be going on.

So, maybe this is a wacky interaction between the "tab" info stored in your previous installations' install receipts and the current codebase, which unfortunately will be awfully hard to reproduce on our side.

**Comment by apjanke** [comment]
> So it seems whatever was causing it got cleaned with brew rm.

My suspicion is that points to an interaction with the install receipt files, which will unfortunately be hard to reproduce on our end. My apologies. :(

Any chance you can do a `brew rm` and clean install on your build boxes?

**Comment by vytis** [comment]
> Any chance you can do a brew rm and clean install on your build boxes?

I could of course, but that would probably clean whatever trace there is of the problem. I could try comparing contents of working directories, but what else is there apart from `/usr/local/Cellar` and `~/Library/Caches/Homebrew`?

**Comment by apjanke** [comment]
> I could of course, but that would probably clean whatever trace there is of the problem.

I'm afraid that might be your best bet here; we just don't have the resources to track down cross-version problems like this.

One last attempt: could you post the contents of your `/usr/local/Cellar/carthage/<version>/INSTALL_RECEIPT.json` from one of the affected boxes? That would be where the relevant data residue is hanging out.

**Comment by vytis** [comment]
> I'm afraid that might be your best bet here; we just don't have the resources to track down cross-version problems like this.

I completely understand this, it seems to be quite an edge case after all.

The last two versions I have installed:

Contents of `carthage/0.26.2/INSTALL_RECEIPT.json`:

```
{
  "homebrew_version": "1.3.5-14-ge1808bf",
  "used_options": [],
  "unused_options": [],
  "built_as_bottle": true,
  "poured_from_bottle": true,
  "installed_as_dependency": false,
  "installed_on_request": true,
  "changed_files": [
    "INSTALL_RECEIPT.json"
  ],
  "time": 1509712208,
  "source_modified_time": 1507946260,
  "HEAD": null,
  "stdlib": "libcxx",
  "compiler": "clang",
  "aliases": [],
  "runtime_dependencies": [],
  "source": {
    "path": "\/usr\/local\/Homebrew\/Library\/Taps\/homebrew\/homebrew-core\/Formula\/carthage.rb",
    "tap": "homebrew\/core",
    "spec": "stable",
    "versions": {
      "stable": "0.26.2",
      "devel": null,
      "head": "HEAD",
      "version_scheme": 0
    }
  }
}
```

Contents of `carthage/0.25.0/INSTALL_RECEIPT.json`:

```
{
  "homebrew_version": "1.3.2-2-ge777010",
  "used_options": [],
  "unused_options": [],
  "built_as_bottle": true,
  "poured_from_bottle": true,
  "installed_as_dependency": null,
  "installed_on_request": true,
  "changed_files": [
    "INSTALL_RECEIPT.json"
  ],
  "time": 1504712153,
  "source_modified_time": 1504549251,
  "HEAD": null,
  "stdlib": "libcxx",
  "compiler": "clang",
  "aliases": [],
  "runtime_dependencies": [],
  "source": {
    "path": "\/usr\/local\/Homebrew\/Library\/Taps\/homebrew\/homebrew-core\/Formula\/carthage.rb",
    "tap": "homebrew\/core",
    "spec": "stable",
    "versions": {
      "stable": "0.25.0",
      "devel": null,
      "head": "HEAD",
      "version_scheme": 0
    }
  }
}
```

**Comment by apjanke** [comment]
> I completely understand this, it seems to be quite an edge case after all.

I appreciate your understanding, because after reading those `INSTALL_RECEIPT.json` files, I've got nothing. Sorry. :(

I think you'd best `brew rm` and do a clean reinstall. If that doesn't work, open up a new issue and we'll get you fixed up. But as is, ¯\_(ツ)_/¯, beats me, and we don't have the resources to pursue it. Sorry.

**Comment by vytis** [comment]
> I think you'd best brew rm and do a clean reinstall. If that doesn't work, open up a new issue and we'll get you fixed up. But as is, ¯\(ツ)/¯, beats me, and we don't have the resources to pursue it. Sorry.

The workaround does the job. No worries, you already spent quite a lot of time chasing this one! Thanks for help and trying to reproduce this one for so long :)

**Comment by apjanke** [comment]
👍 Thanks for your understanding and detailed bug reporting!
