### ISSUE TITLE
brew test bot complains about syntax error in isync Formula on El Capitan

### ISSUE THREAD

**Issue by javian** [Homebrew/brew#661]
In the PHP tap we are running into a problem with the test bot. For some reason it finds an error in the isync formula on El Capitan only. Yosemite and Mavericks built fine for recent PRs

Example snippet from https://bot.brew.sh/job/Homebrew%20PHP%20Pull%20Requests/2072/version=el_capitan/console
```
==> brew uses homebrew/php/drush
==> FAILED
Error: /usr/local/Library/Taps/homebrew/homebrew-core/Formula/isync.rb:9: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/isync.rb:14: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/isync.rb:16: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
Please report this bug:
    https://git.io/brew-troubleshooting

```

**Comment by DomT4** [comment]
Second time in 24 hours, hurrah. Should be fixed now, have rescheduled the builds that hit the issue.

**Comment by UniqMartin** [comment]
I think we might be hitting a variation of #590 here, though I'm not entirely sure why things might have ended up in a conflicting state, as `isync` was pulled exactly like in the PR.

**Comment by DomT4** [comment]
@UniqMartin I haven't looked into it much but my suspicion partly lies with our autoupdate feature, because `HOMEBREW_DEVELOPER` is of course set on CI which means the autoupdate feature will be as well, which triggers on `install`.

So potentially, `brew pull xyz` is stashing & popping changes not in `origin/master` repeatedly throughout a CI run, which I could imagine has the potential for issues. Haven't checked though, so this could be a stupid comment 😄.

**Comment by UniqMartin** [comment]
This sounds entirely plausible and like a strong indicator that we probably should disable the auto-update feature in `brew test-bot`. I cannot quite imagine why we would want to have it enabled during a `brew test-bot` run. Since `brew test-bot` is pulling changes from PRs, thus temporarily creates a divergent `master`, this sounds like a recipe for trouble …

**Comment by javian** [comment]
Thanks for looking into it. It seems that the problem is back again - https://bot.brew.sh/job/Homebrew%20PHP%20Pull%20Requests/2081/version=el_capitan/console .

**Comment by MikeMcQuaid** [comment]
> I cannot quite imagine why we would want to have it enabled during a brew test-bot run. Since brew test-bot is pulling changes from PRs, thus temporarily creates a divergent master, this sounds like a recipe for trouble …

Disabled in 3f7adf2. We'll see if that sorts it out.

**Comment by javian** [comment]
Looks like I'm seeing something similar today https://bot.brew.sh/job/Homebrew%20PHP%20Pull%20Requests/2148/version=mavericks/console but with another formula. Is it related ?

**Comment by apjanke** [comment]
Looks related.

Just a guess, but try rebasing on `master` as a workaround.

**Comment by javian** [comment]
the pr was already rebased against homebrew-php master so that didn't help.
